import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "../../../providers/auth";
import { QueryProvider } from "../../../providers/query";
import Layout from "@/components/Layout/Layout";

import "@/app/globals.css";
import I18nProvider from "@/providers/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string}
}>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextAuthProvider>
          <QueryProvider>
            <I18nProvider locale={locale}>
              <Layout>
                {children}
              </Layout>
            </I18nProvider>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
